### ISSUE TITLE
hostGW模式有问题啊

### ISSUE THREAD

**Issue by xielonglong744** [y805939188/simple-k8s-cni#7]
问题描述：
    使用hostGW模式测试的时候报错信息如下：
              注册 vxlan 模式 cni 成功 
              进入到了 pluginMain 并且没有 err, cmd 是:  ADD 
              进入到 cmdAdd 
              这里的 CmdArgs 是:  ContainerID:  a6f0ef0dfb45 Netns:  /proc/2335/ns/net IfName:  ens37 Args:   Path:  /opt/cni/bin/ StdinData:  {
                "cniVersion": "0.3.0",
                "name": "testcni",
                "type": "testcni",
                "bridge": "testcni0",
                "subnet": "172.31.0.0/16"
              }
               
              创建网卡失败, err:  Link not found 
              执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found 
              给主机添加其他节点网络信息失败, err:  invalid CIDR address:  
              出错的位置在 cni.Bootstrap 
              设置 cni 失败:  invalid CIDR address:

**Comment by y805939188** [comment]
他说 Link not found，大概率是没传网桥名字或者传错了。
