### ISSUE TITLE
无法部署

### ISSUE THREAD

**Issue by LY-today** [y805939188/simple-k8s-cni#9]
您好，我按您的操作文档进行部署，但是没有生效，如果您还关注该项目，您可以回复我一下，我请教几个问题，谢谢您

**Comment by y805939188** [comment]
> 您好，我按您的操作文档进行部署，但是没有生效，如果您还关注该项目，您可以回复我一下，我请教几个问题，谢谢您

能说下你是怎么操作的么？这个项目只能是先把 golang 代码 build 成二进制，然后扔到集群对应的目录下。

**Comment by y805939188** [comment]
编译二进制时候需要注意一下对应的环境。如果本地开发环境和集群环境不一样的话，build 时候需要交叉编译成对应的集群环境

**Comment by LY-today** [comment]
> > 您好，我按您的操作文档进行部署，但是没有生效，如果您还关注该项目，您可以回复我一下，我请教几个问题，谢谢您
> 
> 能说下你是怎么操作的么？这个项目只能是先把 golang 代码 build 成二进制，然后扔到集群对应的目录下。

1. master和worker 机器上到  /etc/cni/net.d/ 目录，创建test-cni.conf文件，内容如下：
```
{
  "cniVersion": "0.3.0",
  "name": "testcni",
  "type": "testcni",
  "bridge": "testcni0",
  "subnet": "10.243.0.0/16"
}
```
2. 本地构建项目：GOOS=linux GOARCH=amd64  go build -o testcni，并将testcni上传到master和worker节点
3. 将testcni放到节点上/opt/cni/bin目录下
4. 创建test-busybox.yaml 项目
5. journalctl -xeu kubelet -f 查看日志（没有看到有调用插件的日志，pod的ip也不是10.243段，而是10.244段）

辛苦您看下操作是否有问题

**Comment by LY-today** [comment]
我的原始需求：让新生成的pod的ip在我指定的ip段
如果您这个项目支持pod销毁重建后，ip不变，那是更好的，如果代码已经支持，您可以告诉我一下如何配置开启

**Comment by LY-today** [comment]
<img width="1668" alt="image" src="https://github.com/y805939188/simple-k8s-cni/assets/33409445/4f500c86-b6d9-4b67-89fd-9e7fb4d04d1f">

**Comment by LY-today** [comment]
哦，我好像知道了，我的/etc/cni/net.d 下有个10-flannel.conflist的文件，cni优先找到是这个插件，现在我把flannel移走了，但是创建pod报错，内容如下：
```
 Warning  FailedCreatePodSandBox  12s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "26750eeb8ba9b7d686e5771f6d4fa019bf4ec0613c558e26282438ff0db1eb16": plugin type="testcni" name="testcni" failed (add): invalid CIDR address:
```

**Comment by LY-today** [comment]
> 哦，我好像知道了，我的/etc/cni/net.d 下有个10-flannel.conflist的文件，cni优先找到是这个插件，现在我把flannel移走了，但是创建pod报错，内容如下：
> 
> ```
>  Warning  FailedCreatePodSandBox  12s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "26750eeb8ba9b7d686e5771f6d4fa019bf4ec0613c558e26282438ff0db1eb16": plugin type="testcni" name="testcni" failed (add): invalid CIDR address:
> ```

<img width="1715" alt="image" src="https://github.com/y805939188/simple-k8s-cni/assets/33409445/cd73c127-d9bf-443a-a8df-3844fa55baf3">

**Comment by LY-today** [comment]
我找到了项目日志：
```
即将注册 vxlan 模式 cni
注册 vxlan 模式 cni 成功
进入到了 pluginMain 并且没有 err, cmd 是:  ADD
进入到 cmdAdd
这里的 CmdArgs 是:  ContainerID:  0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a Netns:  /var/run/netns/cni-dffa73e1-1569-e1fa-d694-06ab86bf6367 IfName:  eth0 Args:  IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=myapp-pod1;K8S_POD_INFRA_CONTAINER_ID=0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a;K8S_POD_UID=42badc43-04c1-4675-9c41-def7dcecc578 Path:  /opt/cni/bin StdinData:  {"bridge":"testcni0","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
创建网卡失败, err:  Link not found
执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found
给主机添加其他节点网络信息失败, err:  invalid CIDR address:
出错的位置在 cni.Bootstrap
设置 cni 失败:  invalid CIDR address:
即将注册 vxlan 模式 cni
注册 vxlan 模式 cni 成功
进入到了 pluginMain 并且没有 err, cmd 是:  DEL
进入到 cmdDel
这里的 CmdArgs 是:  ContainerID:  0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a Netns:  /var/run/netns/cni-dffa73e1-1569-e1fa-d694-06ab86bf6367 IfName:  eth0 Args:  IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=myapp-pod1;K8S_POD_INFRA_CONTAINER_ID=0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a;K8S_POD_UID=42badc43-04c1-4675-9c41-def7dcecc578 Path:  /opt/cni/bin StdinData:  {"bridge":"testcni0","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
```

**Comment by y805939188** [comment]
> 我找到了项目日志：
> 
> ```
> 即将注册 vxlan 模式 cni
> 注册 vxlan 模式 cni 成功
> 进入到了 pluginMain 并且没有 err, cmd 是:  ADD
> 进入到 cmdAdd
> 这里的 CmdArgs 是:  ContainerID:  0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a Netns:  /var/run/netns/cni-dffa73e1-1569-e1fa-d694-06ab86bf6367 IfName:  eth0 Args:  IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=myapp-pod1;K8S_POD_INFRA_CONTAINER_ID=0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a;K8S_POD_UID=42badc43-04c1-4675-9c41-def7dcecc578 Path:  /opt/cni/bin StdinData:  {"bridge":"testcni0","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> 创建网卡失败, err:  Link not found
> 执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found
> 给主机添加其他节点网络信息失败, err:  invalid CIDR address:
> 出错的位置在 cni.Bootstrap
> 设置 cni 失败:  invalid CIDR address:
> 即将注册 vxlan 模式 cni
> 注册 vxlan 模式 cni 成功
> 进入到了 pluginMain 并且没有 err, cmd 是:  DEL
> 进入到 cmdDel
> 这里的 CmdArgs 是:  ContainerID:  0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a Netns:  /var/run/netns/cni-dffa73e1-1569-e1fa-d694-06ab86bf6367 IfName:  eth0 Args:  IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=myapp-pod1;K8S_POD_INFRA_CONTAINER_ID=0269b4debbd5a0859e98f7b77beccfd5460b6a0cacc8114b8e6bd8a617d43b3a;K8S_POD_UID=42badc43-04c1-4675-9c41-def7dcecc578 Path:  /opt/cni/bin StdinData:  {"bridge":"testcni0","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> ```

nettools.go 里头有个 CreateBridge 函数，你可以尝试把前几行代码大概第 313~321 行注释掉再试试看。这几行是一进来就尝试根据 brName 获取网桥设备，如果此时没有网桥设备的话，有可能会报错。我也忘了当时为啥这么写，也有可能就是单纯的 bug。另外你可以根据这个 log 文件定位大概是哪里出问题了，然后自己再增加一些日志以方便自己 debug。还有就是 test 目录下有个 main_test.go，如果我没记错的话这个文件你可以直接在节点上利用 vscode 做单节点的断点 debug，可以尝试对这个文件做断点以调试问题。

**Comment by LY-today** [comment]
现在报错发生了变化
```
即将注册 vxlan 模式 cni
注册 vxlan 模式 cni 成功
进入到了 pluginMain 并且没有 err, cmd 是:  ADD
进入到 cmdAdd
这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
netlink LinkByName 报错:  testcni0 err:  Link not found
创建网卡失败, err:  Link not found
执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found
获取本机网卡信息失败, err:  no valid network device found
出错的位置在 cni.Bootstrap
设置 cni 失败:  no valid network device found
即将注册 vxlan 模式 cni
注册 vxlan 模式 cni 成功
进入到了 pluginMain 并且没有 err, cmd 是:  DEL
进入到 cmdDel
这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
```

**Comment by y805939188** [comment]
> 现在报错发生了变化
> 
> ```
> 即将注册 vxlan 模式 cni
> 注册 vxlan 模式 cni 成功
> 进入到了 pluginMain 并且没有 err, cmd 是:  ADD
> 进入到 cmdAdd
> 这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> netlink LinkByName 报错:  testcni0 err:  Link not found
> 创建网卡失败, err:  Link not found
> 执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found
> 获取本机网卡信息失败, err:  no valid network device found
> 出错的位置在 cni.Bootstrap
> 设置 cni 失败:  no valid network device found
> 即将注册 vxlan 模式 cni
> 注册 vxlan 模式 cni 成功
> 进入到了 pluginMain 并且没有 err, cmd 是:  DEL
> 进入到 cmdDel
> 这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> ```

因为我这里没有你的环境，很难复现你的问题。所以我建议你:
1. 最好准备一个干净的没装过任何网络插件的集群环境。如果你装过某些插件的话那很可能插件已经在节点上设置过一些网络配置了，可能造成影响
2. 自己在代码中多增加一些感兴趣的日志
3. 使用 main_test.go 做断点 debug，这样能看到代码进行到哪一步，做了什么操作
4. 多利用 `ip` 或者 `ifconfig` 还有 `iptables` 之类的 Linux 命令来查看网络以及网络设备的状态。比如代码中执行了获取网桥的操作并且失败了，那你就可以通过 `ip link show` 查看是否真的存在这个网桥。再比如代码里创建 veth 设备失败了，你可以 `ip link add` 命令尝试直接创建设备看是否会出错。总之可以通过调试代码 + 手动执行命令的方式配合着来查问题，能加深对这玩意儿的理解。

**Comment by LY-today** [comment]
> > 现在报错发生了变化
> > ```
> > 即将注册 vxlan 模式 cni
> > 注册 vxlan 模式 cni 成功
> > 进入到了 pluginMain 并且没有 err, cmd 是:  ADD
> > 进入到 cmdAdd
> > 这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> > netlink LinkByName 报错:  testcni0 err:  Link not found
> > 创建网卡失败, err:  Link not found
> > 执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found
> > 获取本机网卡信息失败, err:  no valid network device found
> > 出错的位置在 cni.Bootstrap
> > 设置 cni 失败:  no valid network device found
> > 即将注册 vxlan 模式 cni
> > 注册 vxlan 模式 cni 成功
> > 进入到了 pluginMain 并且没有 err, cmd 是:  DEL
> > 进入到 cmdDel
> > 这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> > ```
> 
> 因为我这里没有你的环境，很难复现你的问题。所以我建议你:
> 
> 1. 最好准备一个干净的没装过任何网络插件的集群环境。如果你装过某些插件的话那很可能插件已经在节点上设置过一些网络配置了，可能造成影响
> 2. 自己在代码中多增加一些感兴趣的日志
> 3. 使用 main_test.go 做断点 debug，这样能看到代码进行到哪一步，做了什么操作
> 4. 多利用 `ip` 或者 `ifconfig` 还有 `iptables` 之类的 Linux 命令来查看网络以及网络设备的状态。比如代码中执行了获取网桥的操作并且失败了，那你就可以通过 `ip link show` 查看是否真的存在这个网桥。再比如代码里创建 veth 设备失败了，你可以 `ip link add` 命令尝试直接创建设备看是否会出错。总之可以通过调试代码 + 手动执行命令的方式配合着来查问题，能加深对这玩意儿的理解。

感谢您的回复，我稍后进行断点调试

**Comment by y805939188** [comment]
> > > 现在报错发生了变化
> > > ```
> > > 即将注册 vxlan 模式 cni
> > > 注册 vxlan 模式 cni 成功
> > > 进入到了 pluginMain 并且没有 err, cmd 是:  ADD
> > > 进入到 cmdAdd
> > > 这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> > > netlink LinkByName 报错:  testcni0 err:  Link not found
> > > 创建网卡失败, err:  Link not found
> > > 执行创建网桥, 创建 veth 设备, 添加默认路由等操作失败, err:  Link not found
> > > 获取本机网卡信息失败, err:  no valid network device found
> > > 出错的位置在 cni.Bootstrap
> > > 设置 cni 失败:  no valid network device found
> > > 即将注册 vxlan 模式 cni
> > > 注册 vxlan 模式 cni 成功
> > > 进入到了 pluginMain 并且没有 err, cmd 是:  DEL
> > > 进入到 cmdDel
> > > 这里的 CmdArgs 是:  ContainerID:  6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d Netns:  /var/run/netns/cni-cb6647cd-7110-881d-b93a-6c3ffce1a028 IfName:  eth0 Args:  K8S_POD_NAME=myapp-pod2;K8S_POD_INFRA_CONTAINER_ID=6b5be95b5f09a67213a8feb3768031b61c38d9e6e0328cee32ffc2880ca40d6d;K8S_POD_UID=3b5aa9d5-cd52-4b3b-9171-c260fc19ad61;IgnoreUnknown=1;K8S_POD_NAMESPACE=default Path:  /opt/cni/bin StdinData:  {"bridge":"testcni","cniVersion":"0.3.1","name":"testcni","subnet":"10.251.207.0/24","type":"testcni"}
> > > ```
> > 
> > 
> > 因为我这里没有你的环境，很难复现你的问题。所以我建议你:
> > 
> > 1. 最好准备一个干净的没装过任何网络插件的集群环境。如果你装过某些插件的话那很可能插件已经在节点上设置过一些网络配置了，可能造成影响
> > 2. 自己在代码中多增加一些感兴趣的日志
> > 3. 使用 main_test.go 做断点 debug，这样能看到代码进行到哪一步，做了什么操作
> > 4. 多利用 `ip` 或者 `ifconfig` 还有 `iptables` 之类的 Linux 命令来查看网络以及网络设备的状态。比如代码中执行了获取网桥的操作并且失败了，那你就可以通过 `ip link show` 查看是否真的存在这个网桥。再比如代码里创建 veth 设备失败了，你可以 `ip link add` 命令尝试直接创建设备看是否会出错。总之可以通过调试代码 + 手动执行命令的方式配合着来查问题，能加深对这玩意儿的理解。
> 
> 感谢您的回复，我稍后进行断点调试

👍 👍 👍
